---

- hosts: all
  sudo: yes
  roles:
    - docker

- hosts: lbservers
  sudo: yes
  roles:
    - nginx

- hosts: magnolia-authors
  sudo: yes
  vars:
    instance_type: author
    db_type: mysql
  roles:
    - mysql
    - { role: magnolia, count: 1}

- hosts: magnolia-publics
  sudo: yes
  vars:
    instance_type: public
    db_type: mysql_cluster
  roles:
    - mysql
    - { role: magnolia, count: "{{ cluster_node_count }}" }
