---

- hosts: all
  sudo: yes
  roles:
    - docker

# - hosts: lbservers
#   sudo: yes
#   roles:
#     - haproxy

- hosts: magnolia-authors
  sudo: yes
  vars:
    count: 1
    instance_type: author
    db_type: mysql
  roles:
    - mysql
    - magnolia

- hosts: magnolia-publics
  sudo: yes
  vars:
    count: "{{ cluster_node_count|default(1)|int }}"
    instance_type: public
    db_type: mysql_cluster
  roles:
    - mysql
    - magnolia
